name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, windows]

    # Add environment variables here (they will be available to the app)
    env:
      PORT: 3000
      APP_MESSAGE: "Deployed via GitHub Actions (self-hosted runner)"

    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          run-id: ${{ github.event.workflow_run.id }}
          path: ./artifact

      - name: Unzip artifact
        shell: pwsh
        run: |
          if (Test-Path .\deploy) { Remove-Item -Recurse -Force .\deploy }
          New-Item -ItemType Directory -Path .\deploy | Out-Null
          Expand-Archive -Path .\artifact\app-dist.zip -DestinationPath .\deploy -Force

      - name: Setup Node.js on runner
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pm2 globally
        shell: pwsh
        run: npm install -g pm2

      - name: Install production deps
        shell: pwsh
        run: |
          cd deploy
          npm ci --omit=dev

      - name: Restart app with pm2
        shell: pwsh
        run: |
          cd deploy
          pm2 delete node-ci-cd-assignment || echo "no previous app"
          pm2 start app.js --name node-ci-cd-assignment --update-env
          pm2 save

      - name: PM2 status
        shell: pwsh
        run: pm2 status
